# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HoppCli < Formula
  desc "CLI for Hoppscotch.io"
  homepage "https://github.com/hoppscotch/hopp-cli"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.8/hopp-cli_0.0.8_macOS_arm64.tar.gz"
      sha256 "d43daad92c3716b792ea867d903c7af8ab4e800732d2d70c7fa0a41c3c5cce96"

      def install
        bin.install "hopp-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.8/hopp-cli_0.0.8_macOS_x86_64.tar.gz"
      sha256 "18a0a110b8d61e186ea6b2e3790fffecbe90a3ced0d6ddf4ed37e676178a386b"

      def install
        bin.install "hopp-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.8/hopp-cli_0.0.8_linux_arm64.tar.gz"
      sha256 "9730d3a1bc56cee0bc88d2dd517c58a8e539485881c93048802f0451a43f18e6"

      def install
        bin.install "hopp-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.8/hopp-cli_0.0.8_linux_x86_64.tar.gz"
      sha256 "73fe8bf58fc5f9483ac937858c27b38ebd056ce6febb3bd9ea9c9b75e64a0ee1"

      def install
        bin.install "hopp-cli"
      end
    end
  end
end
