# This file was generated by GoReleaser. DO NOT EDIT.
class HoppCli < Formula
  desc "CLI for Hoppscotch.io"
  homepage "https://github.com/hoppscotch/hopp-cli"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.6/hopp-cli_0.0.6_Darwin_x86_64.tar.gz"
    sha256 "32b67c173e0f81fd589efd79f42be81a105a17bb5f116b6302df423464551dab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.6/hopp-cli_0.0.6_Linux_x86_64.tar.gz"
      sha256 "97129f8e01c735b90117a424141de5b07118cf7e820cd67b2328cba95baf01da"
    end
  end

  def install
    bin.install "hopp-cli"
  end
end
