# This file was generated by GoReleaser. DO NOT EDIT.
class HoppCli < Formula
  desc "CLI for Hoppscotch.io"
  homepage "https://github.com/hoppscotch/hopp-cli"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.7/hopp-cli_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "d9397b55af0878843ce8868031277c10fdacbbace941a3b7af4d0647683f09d9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoppscotch/hopp-cli/releases/download/v0.0.7/hopp-cli_0.0.7_Linux_x86_64.tar.gz"
      sha256 "4b187b083ac6cb159f7725b9d254e4f915ec7de512dbfde5e11688bbf37d3622"
    end
  end

  def install
    bin.install "hopp-cli"
  end
end
