# This file was generated by GoReleaser. DO NOT EDIT.
class Pwcli < Formula
  desc "Postwoman CLI in Go"
  homepage "https://github.com/athul/pwcli"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/athul/pwcli/releases/download/v0.0.3/pwcli_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "724ee29877a791260c54792385cbc3d855794896ae998c5ea698907f1fd61b3e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/athul/pwcli/releases/download/v0.0.3/pwcli_0.0.3_Linux_x86_64.tar.gz"
      sha256 "c0b66daab9957e662d7585fb43f3b326fe71a34b426681749382ec8b5c28f2e5"
    end
  end

  def install
    bin.install "pwcli"
  end
end
