# This file was generated by GoReleaser. DO NOT EDIT.
class Pwcli < Formula
  desc "Postwoman CLI in Go"
  homepage "https://github.com/athul/pwcli"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/athul/pwcli/releases/download/v0.0.1/pwcli_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "8dc64c372e019dc8a6996897ac485e645819cecae1edd0cef662227cb7dab9b1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/athul/pwcli/releases/download/v0.0.1/pwcli_0.0.1_Linux_x86_64.tar.gz"
      sha256 "052dc50dcc9495128b233fed4a563f26b90935382c039617bb966912403619b0"
    end
  end

  def install
    bin.install "pwcli"
  end
end
