# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelby < Formula
  desc "A fast and minimal Shell Prompt in Go"
  homepage "https://github.com/athul/shelby"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/athul/shelby/releases/download/v1.0.3/shelby_1.0.3_Darwin_amd64.tar.gz"
      sha256 "072d91f5911ce234836bcf468aafe1d4f36d9abf81a3b65359b3d3314aa39a64"

      def install
        bin.install "shelby"%
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/athul/shelby/releases/download/v1.0.3/shelby_1.0.3_Darwin_arm64.tar.gz"
      sha256 "20e63fd08fe4c3648e2700b797cecc612b304f102f2690e874f597ad36999f0d"

      def install
        bin.install "shelby"%
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/athul/shelby/releases/download/v1.0.3/shelby_1.0.3_Linux_amd64.tar.gz"
      sha256 "ee64a9d7c4b2ac8c9ab805694fd1b7a8712447153a9764ca5e42c2dfbc66c711"

      def install
        bin.install "shelby"%
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/athul/shelby/releases/download/v1.0.3/shelby_1.0.3_Linux_arm64.tar.gz"
      sha256 "1418766aa4e1554c6112337fe692c5e87a60c9d78e4547ba755aa579b22a0b4b"

      def install
        bin.install "shelby"%
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/athul/shelby/releases/download/v1.0.3/shelby_1.0.3_Linux_armv6.tar.gz"
      sha256 "d9f08846f1e6ddf6270907f3d106288a256311bd9c6d13f8037ac68ca84dd0e6"

      def install
        bin.install "shelby"%
      end
    end
  end
end
